apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: gitea
type: Opaque
data:
  # These are example values, you should replace them with your own base64 encoded values
  # To generate: echo -n "your-password" | base64
  POSTGRES_USER: Z2l0ZWE=           # 'gitea' in base64
  POSTGRES_PASSWORD: Y2hhbmdlbWU=   # 'changeme' in base64
  POSTGRES_DB: Z2l0ZWE=             # 'gitea' in base64