apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
type: Opaque
stringData:
  # Admin credentials
  admin-username: gitea_admin
  admin-password: r8sA8CPHD9!bt6d
  admin-email: gitea@local.domain
  
  # Database credentials
  postgresql-password: gitea
  postgresql-repmgr-password: changeme2
  postgresql-postgres-password: changeme1
  postgresql-pgpool-admin-password: changeme3
  
  # Redis credentials
  redis-password: changeme