# Minimal overrides for Gitea
ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: gitea.conxtor.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - gitea.conxtor.com
      secretName: gitea-tls

gitea:
  admin:
    existingSecret: gitea-secrets
    username: ${admin-username}
    password: ${admin-password}
    email: ${admin-email}
    passwordMode: keepUpdated

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        password:
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: postgresql-password
        database: gitea
        username: gitea

postgresql-ha:
  enabled: false

redis:
  enabled: true
  architecture: standalone
  global:
    redis:
      password:
        valueFrom:
          secretKeyRef:
            name: gitea-secrets
            key: redis-password

redis-cluster:
  enabled: false

actions:
  enabled: true