apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

commonLabels:
  env: production

resources:
  - ../../base/mariadb
  - ../../base/gitea
  - namespace.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: .*
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path