apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

commonLabels:
  environment: production

resources:
  - ../../base/mariadb
  - ../../base/gitea
  - namespace.yaml

patches:
  - target:
      kind: Ingress
      name: gitea
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: git.conxtor.com
      - op: replace
        path: /spec/rules/0/host
        value: git.conxtor.com