apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod

    [repository]
    ROOT = /data/gitea/repositories
    DEFAULT_BRANCH = main

    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /data/gitea/uploads

    [server]
    DOMAIN = git.conxtor.com
    SSH_DOMAIN = git.conxtor.com
    HTTP_PORT = 3000
    ROOT_URL = https://git.conxtor.com/
    DISABLE_SSH = false
    SSH_PORT = 2222
    SSH_LISTEN_PORT = 2222
    START_SSH_SERVER = true
    LFS_START_SERVER = true
    LFS_JWT_SECRET = ${LFS_JWT_SECRET}
    OFFLINE_MODE = false

    [database]
    DB_TYPE = mysql
    HOST = mariadb:3306
    NAME = gitea
    USER = gitea
    PASSWD = ${DB_PASSWORD}
    SSL_MODE = disable
    CHARSET = utf8mb4
    
    [security]
    INSTALL_LOCK = true
    SECRET_KEY = ${SECURITY_KEY}
    INTERNAL_TOKEN = ${INTERNAL_TOKEN}

    [service]
    DISABLE_REGISTRATION = false
    REQUIRE_SIGNIN_VIEW = true
    
    [oauth2]
    JWT_SECRET = ${JWT_SECRET}

    [session]
    PROVIDER = file
    
    [log]
    MODE = console
    LEVEL = info
    
    [attachment]
    PATH = /data/gitea/attachments

    [mailer]
    ENABLED = false

    [picture]
    AVATAR_UPLOAD_PATH = /data/gitea/avatars