apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod
    
    [repository]
    ROOT = /data/gitea/repositories
    
    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo
    
    [repository.upload]
    TEMP_PATH = /data/gitea/uploads
    
    [server]
    DOMAIN = git.conxtor.com
    SSH_DOMAIN = git.conxtor.com
    HTTP_PORT = 3000
    ROOT_URL = https://git.conxtor.com/
    DISABLE_SSH = false
    SSH_PORT = 32222
    SSH_LISTEN_PORT = 32222
    LFS_START_SERVER = true
    
    [database]
    DB_TYPE = sqlite3
    PATH = /data/gitea/db/gitea.db
    CHARSET = utf8mb4
    
    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve
    
    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    
    [picture]
    AVATAR_UPLOAD_PATH = /data/gitea/avatars
    
    [attachment]
    PATH = /data/gitea/attachments
    
    [log]
    MODE = console
    LEVEL = debug
    ROOT_PATH = /data/gitea/log
    
    [security]
    INSTALL_LOCK = true
    SECRET_KEY = ${GITEA_SECRET_KEY}
    INTERNAL_TOKEN = ${GITEA_INTERNAL_TOKEN}
    
    [service]
    DISABLE_REGISTRATION = true
    REQUIRE_SIGNIN_VIEW = false
    
    [oauth2]
    JWT_SECRET = ${GITEA_JWT_SECRET}
    
    [metrics]
    ENABLED = true