apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-directories
          image: busybox
          command:
            - sh
            - -c
            - |
              # Create Gitea directories
              mkdir -p /data/gitea/conf
              mkdir -p /data/gitea/db
              mkdir -p /data/gitea/repositories
              mkdir -p /data/gitea/tmp/local-repo
              mkdir -p /data/gitea/uploads
              mkdir -p /data/gitea/indexers
              mkdir -p /data/gitea/sessions
              mkdir -p /data/gitea/avatars
              mkdir -p /data/gitea/attachments
              mkdir -p /data/gitea/log
              
              # Create and set permissions for s6 directory
              mkdir -p /data/.s6-svscan
              
              # Set ownership for all directories
              chown -R 1000:1000 /data
              
              # Set directory permissions
              chmod -R 770 /data/gitea
              chmod 760 /data/gitea/db
              
              # Ensure s6 directory is writable
              chmod 770 /data/.s6-svscan
              
              # Create home directory for git user
              mkdir -p /data/git
              chown 1000:1000 /data/git
              chmod 770 /data/git
          volumeMounts:
            - name: gitea-data
              mountPath: /data
          securityContext:
            runAsUser: 0
      containers:
        - name: gitea
          image: gitea/gitea:1.21
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 32222
              name: ssh
          envFrom:
            - secretRef:
                name: gitea-secret
          env:
            - name: HOME
              value: /data/git
          volumeMounts:
            - name: gitea-data
              mountPath: /data
            - name: gitea-config
              mountPath: /data/gitea/conf/app.ini
              subPath: app.ini
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: gitea-config
          configMap:
            name: gitea-config