apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      initContainers:
        - name: init-directories
          image: busybox:1.36
          command: ['sh', '-c', 'mkdir -p /data/gitea/conf /data/gitea/repositories /data/gitea/tmp /data/gitea/uploads /data/gitea/attachments /data/gitea/avatars && chown -R 1000:1000 /data']
          volumeMounts:
            - name: gitea-data
              mountPath: /data
      containers:
        - name: gitea
          image: gitea/gitea:1.21
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 2222
              name: ssh
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: GITEA__database__DB_TYPE
              value: "mysql"
            - name: GITEA__database__HOST
              value: "mariadb:3306"
            - name: GITEA__database__NAME
              value: "gitea"
            - name: GITEA__database__USER
              value: "gitea"
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: mariadb-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: mariadb-password
            - name: SECURITY_KEY
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: security-key
            - name: INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: internal-token
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: jwt-secret
            - name: LFS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: lfs-jwt-secret
          volumeMounts:
            - name: gitea-data
              mountPath: /data
            - name: gitea-config
              mountPath: /data/gitea/conf/app.ini
              subPath: app.ini
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /api/healthz
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: gitea-config
          configMap:
            name: gitea-config