apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: gitea
  app.kubernetes.io/part-of: gitea

resources:
  - pvc.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: gitea/gitea
    newName: gitea/gitea
    newTag: "1.21"