apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
type: Opaque
stringData:
  GITEA_SECRET_KEY: "umoh1zaev3neishie4jiquievah5ieS6"
  GITEA_INTERNAL_TOKEN: "eifohdaib4ubaefeche4Ot3eiDiphohr"
  GITEA_JWT_SECRET: "eiphie9oe8oidib4aiveuvauGauNgu1iey2coochaejaecahwai0Phiwieme2adu"