apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: ssh
      port: 32222
      targetPort: ssh
      nodePort: 32222
      protocol: TCP
  selector:
    app: gitea
  type: NodePort