apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  my.cnf: |
    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    innodb_buffer_pool_size = 256M
    max_connections = 500
    
    [client]
    default-character-set = utf8mb4
    
    [mysql]
    default-character-set = utf8mb4