apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake
            - --max-allowed-packet=128M
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              value: "gitea"
            - name: MYSQL_USER
              value: "gitea"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secrets
                  key: mariadb-password
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc