apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: database
  app.kubernetes.io/name: mariadb
  app.kubernetes.io/part-of: gitea

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - secret.yaml