apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: mariadb
  app.kubernetes.io/part-of: gitea

resources:
  - pvc.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: mariadb
    newName: mariadb
    newTag: "10.11"